#!/bin/bash
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -i|--input)
        input="$2";
        shift ;;
        -h|--help)
        echo -e "-i --input\n  the job log file for running jupyter notebook\n";
        exit 0 ;;
        *) echo "Unknown parameter passed: $1";  exit 0 ;;
    esac
    shift
done

if [ -z ${input} ]; then echo "no input log set";exit 1; fi
url=$(cat $input|grep localhost|awk '{gsub(/localhost/,"140.114.97.192")}1'|tail -n 1)
printf "To access the notebook,  copy and paste one of these URLs in a browser:\n $url\n"
