version: v1
mig-configs:
  custom-config:
    - devices: [0,1]
      mig-enabled: false
      mig-devices: {}
    - devices: [2,3]
      mig-enabled: true
      mig-devices:
        "2g.10gb": 2
        "3g.20gb": 1
    - devices: [4,5,6,7]
      mig-enabled: true
      mig-devices:
        "1g.5gb": 7