# Generated by Django 4.2 on 2023-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axtasyuser',
            name='permission_level',
            field=models.IntegerField(null=True, verbose_name=range(1, 3)),
        ),
    ]
