# Generated by Django 4.2 on 2023-06-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_axtasyuser_permission_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
