# Generated by Django 5.0.2 on 2024-03-02 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('ip', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gpu', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('cpu', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('gpu', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('cpu', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
